## Linear Regression with multiple variables aka Multivariate regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv('Home_price2.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [4]:
df.bedrooms.fillna(median_bedrooms, inplace = True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df[["area", 'bedrooms', 'age']], df.price)

LinearRegression()

In [6]:
reg.predict([[3000,3,40]])

array([444400.])

In [7]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [8]:
reg.intercept_

383724.9999999998

In [9]:
reg.predict([[2500,4,5]])

array([588625.])

## Exercise

In [84]:
!pip install word2number

In [85]:
from word2number import w2n

In [86]:
print (w2n.word_to_num("one"))

1


In [97]:
df1 = pd.read_csv('Hiring.csv')
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [98]:
df1.experience.fillna('one', inplace=True)

In [99]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        one                    8.0                           9      50000
1        one                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [100]:
df1.experience = df1.experience.apply(w2n.word_to_num)

In [101]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           1                    8.0                           9      50000
1           1                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [120]:
import math
median_test_score = math.floor(df1['test_score(out of 10)'].mean())
df1['test_score(out of 10)'].fillna(median_test_score)


0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [122]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           1                    8.0                           9      50000
1           1                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [123]:
reg1 = linear_model.LinearRegression()
reg1.fit(df1[['experience','test_score(out of 10)', 'interview_score(out of 10)']], df1['salary($)'])

LinearRegression()

In [124]:
reg1.predict([[2,9,6]])

array([51375.54064819])

In [125]:
reg1.predict([[12,10,10]])

array([93523.67002192])

In [126]:
reg1.coef_

array([3031.1979513 , 1893.22650937, 2485.73083785])

In [79]:
reg1.intercept_

17737.26346433771